# Remote working

## Why I won't go back to the office

## Facilitating team trust online 

- [Playing geoguessr](https://www.geoguessr.com/)
- Coworking hours
- Being willing to just hop on a call

## Randomised Coffee Trials (RCT)

- We use these at The Strategy Unit to encourage cross-team chats.
- RainbowR also [use a buddy scheme](https://rainbowr.org/buddies.html) to get community members to connect.
- My PhD scheme has used it to allow current students to network with alumni

## How to run a good team standup 

We have a team meeting every Monday. We like to check in on how everyone is, but as the team has grown, not everyone has time to speak. This is what we currently do.

In advance of the weekly stand-up, all team members share a short summary, in Slack, answering the following questions:

- ⭐ What went well last week
- 🦉 What lessons did you learn
- 🎯 Goal(s) for this week

Two folk are randomly selected to actually speak in the meeting. This keeps standups not too long, whilst making sure it's not just the same voices always sharing.

We encourage **reflection** over **listing**, for example;

- ❌ C&C was good, nice retro, did some inputs dev, caught up on my emails.
- ✅ I've been practicing being less self-deprecating in meetings and successfully did a coffee & code session without down-talking my ability 🙌
